# Generated by Django 5.0.7 on 2024-07-30 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=255, unique=True)),
                ('campaign_name', models.CharField(max_length=255)),
                ('objective', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adset_id', models.CharField(max_length=255, unique=True)),
                ('adset_name', models.CharField(max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='myapp.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='DailyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('spend', models.FloatField()),
                ('reach', models.IntegerField()),
                ('impressions', models.IntegerField()),
                ('frequency', models.FloatField()),
                ('cpm', models.FloatField()),
                ('total_messaging_connection', models.IntegerField()),
                ('link_clicks', models.IntegerField()),
                ('landing_page_views', models.IntegerField()),
                ('leads', models.IntegerField()),
                ('adds_to_cart', models.IntegerField()),
                ('checkouts_initiated', models.IntegerField()),
                ('purchases', models.IntegerField()),
                ('purchases_conversion_value', models.FloatField()),
                ('video_watches_25', models.IntegerField()),
                ('video_watches_50', models.IntegerField()),
                ('video_watches_75', models.IntegerField()),
                ('video_watches_95', models.IntegerField()),
                ('adset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_insights', to='myapp.adset')),
            ],
            options={
                'unique_together': {('adset', 'day')},
            },
        ),
    ]
