# Generated by Django 5.0.7 on 2024-08-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nome_da_empresa', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18)),
                ('faturamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_do_contrato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_de_contrato', models.IntegerField(help_text='Tempo de contrato em meses')),
            ],
        ),
    ]
